### ISSUE TITLE
[LEAGUE LOADER]: Fleaflicker support

### ISSUE THREAD

**Issue by lilkeeps11** [joeyagreco/leeger#62]
### Fantasy Site Name

Fleaflicker

### Fantasy Site URL

https://www.fleaflicker.com/

**Comment by joeyagreco** [comment]
Thanks for opening this issue.

I will work on adding this.

For testing, since I do not have a Fleaflicker league to test on, could you attach your league ID to this issue so I can test with it?

[How to find your league ID](https://cran.r-project.org/web/packages/ffscrapr/vignettes/fleaflicker_basics.html#:~:text=In%20Fleaflicker%2C%20you%20can%20find,%2Fnfl%2Fleagues%2F312861.)

**Comment by lilkeeps11** [comment]
No problem! Thanks for getting to it so quick!  My league ID is 207555Sent from my iPhone, I apologize for any typos.On Oct 25, 2022, at 10:36, Joey Greco ***@***.***> wrote:﻿
@lilkeeps11
Thanks for opening this issue.
I will work on adding this.
For testing, since I do not have a Fleaflicker league to test on, could you attach your league ID to this issue so I can test with it?
How to find your league ID

**Comment by joeyagreco** [comment]
@lilkeeps11 

I have added support for Fleaflicker leagues in version [1.9.0](https://github.com/joeyagreco/leeger/releases/tag/v1.9.0).

I tested with your league ID and it seems to be working fine.

Please open an issue if you run into any bugs.


Make sure you are running the latest version of leeger before running this by using the command: `pip install leeger --upgrade` to ensure you are on version 1.9.0.
